# Generated by Django 5.1.7 on 2025-04-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_subplanfeature_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subplanfeature',
            options={'ordering': ['-order'], 'verbose_name_plural': 'Plan Features'},
        ),
    ]
