# Generated by Django 5.1.7 on 2025-04-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_subplanfeature_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='pwd',
            new_name='password',
        ),
    ]
