# Generated by Django 5.1.7 on 2025-04-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_pwd_trainer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
